spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: autoservice-api

logging:
  level:
    root: INFO
    com.autoservice: DEBUG

server:
  port: 8080
